In [32]:
import numpy as np
from numpy.random import seed
from IPython.core.debugger import set_trace

In [3]:
class OriginalModel():
    def __init__(self, w0, w1, w2, w3):
        self.w0 = w0
        self.w1 = w1
        self.w2 = w2
        self.w3 = w3
        
    def predict(self, X):
        return (self.w0 + self.w1*X[0] + self.w2*X[1] + self.w3*X[2])

In [35]:
from numpy.random import seed

class AdalineSGD(object):
    def __init__(self, eta=0.01, n_iter=10, shuffle=True, random_state=None):
        self.eta = eta
        self.n_iter = n_iter
        self.w_initialized = False
        self.shuffle = shuffle
        if random_state:
            seed(random_state)
        
    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)
        self._initialize_weights(X.shape[1])
        self.cost_ = []
        for i in range(self.n_iter):
            if self.shuffle:
                X, y = self._shuffle(X, y)
            cost = []
            for xi, target in zip(X, y):
                set_trace()
                cost.append(self._update_weights(xi, target))
            avg_cost = sum(cost) / len(y)
            self.cost_.append(avg_cost)
        return self

    def partial_fit(self, X, y):
        X = np.array(X)
        y = np.array(y)
        """Fit training data without reinitializing the weights"""
        if not self.w_initialized:
            self._initialize_weights(X.shape[1])
        if y.ravel().shape[0] > 1:
            for xi, target in zip(X, y):
                self._update_weights(xi, target)
        else:
            self._update_weights(X, y)
        return self

    def _shuffle(self, X, y):
        X = np.array(X)
        y = np.array(y)
        """Shuffle training data"""
        r = np.random.permutation(len(y))
        return X[r], y[r]
    
    def _initialize_weights(self, m):
        """Initialize weights to zeros"""
        self.w_ = np.zeros(1 + m)
        self.w_initialized = True
        
    def _update_weights(self, xi, target):
        """Apply Adaline learning rule to update the weights"""
        set_trace()
        output = self.net_input(xi)
        error = (target - output)
        self.w_[1:] += self.eta * xi.dot(error)
        self.w_[0] += self.eta * error
        cost = 0.5 * error**2
        return cost
    
    def net_input(self, X):
        X = np.array(X)
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def activation(self, X):
        """Compute linear activation"""
        return self.net_input(X)

    def predict(self, X):
        X = np.array(X)
        """Return class label after unit step"""
        return np.where(self.activation(X) >= 0.0, 1, -1)

In [9]:
previous_data[:2]

array([[    nan,     nan,     nan,     nan],
       [  57.82,   26.13,   67.  , 2346.  ]])

In [29]:
len(y_prev)

799

In [30]:
len(X_prev)

799

In [ ]:
test_iterations = 30
previous_data = np.genfromtxt('model_input.csv', delimiter=',')
incoming_data = np.genfromtxt('incoming_data.csv', delimiter=',')

w0 = 718.91565187
w1 = -18.87648056
w2 = -25.9855236
w3 = -27.87443884

origin_clf = OriginalModel(w0, w1, w2, w3)
new_clf = AdalineSGD()

# train model initially
X_prev = [x[:-1] for x in previous_data]
y_prev = [x[len(x)-1:] for x in previous_data]

# remove header row
# change types
X_prev = [list(map(float, x)) for x in X_prev[1:]]

# change type of y to int
y_prev = [int(y[0]) for y in y_prev[1:]]

# train model
new_clf.fit(X_prev, y_prev)

for i in range(test_iterations):
    # compute model and update model incrimentally
    
    # original model predictions
    

> /tmp/ipykernel_51824/1957752173.py(23)fit()
     21             for xi, target in zip(X, y):
     22                 set_trace()
---> 23                 cost.append(self._update_weights(xi, target))
     24             avg_cost = sum(cost) / len(y)
     25             self.cost_.append(avg_cost)



ipdb>  xi


array([51.1 , 25.38, 56.  ])


ipdb>  target


2576


ipdb>  s


--Call--
> /tmp/ipykernel_51824/1957752173.py(53)_update_weights()
     51         self.w_initialized = True
     52 
---> 53     def _update_weights(self, xi, target):
     54         """Apply Adaline learning rule to update the weights"""
     55         set_trace()



ipdb>  xi


array([51.1 , 25.38, 56.  ])


ipdb>  target


2576


ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(55)_update_weights()
     53     def _update_weights(self, xi, target):
     54         """Apply Adaline learning rule to update the weights"""
---> 55         set_trace()
     56         output = self.net_input(xi)
     57         error = (target - output)



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(56)_update_weights()
     54         """Apply Adaline learning rule to update the weights"""
     55         set_trace()
---> 56         output = self.net_input(xi)
     57         error = (target - output)
     58         self.w_[1:] += self.eta * xi.dot(error)



ipdb>  xi


array([51.1 , 25.38, 56.  ])


ipdb>  s


--Call--
> /tmp/ipykernel_51824/1957752173.py(63)net_input()
     61         return cost
     62 
---> 63     def net_input(self, X):
     64         X = np.array(X)
     65         """Calculate net input"""



ipdb>  X


array([51.1 , 25.38, 56.  ])


ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(64)net_input()
     62 
     63     def net_input(self, X):
---> 64         X = np.array(X)
     65         """Calculate net input"""
     66         return np.dot(X, self.w_[1:]) + self.w_[0]



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(66)net_input()
     64         X = np.array(X)
     65         """Calculate net input"""
---> 66         return np.dot(X, self.w_[1:]) + self.w_[0]
     67 
     68     def activation(self, X):



ipdb>  X


array([51.1 , 25.38, 56.  ])


ipdb>  np.dot(X, self.w_[1:]) + self.w_[0]


0.0


ipdb>  self.w_[1:]


array([0., 0., 0.])


ipdb>  s


--Call--
> <__array_function__ internals>(2)dot()



ipdb>  n


> <__array_function__ internals>(4)dot()



ipdb>  s


--Call--
> /home/jloesch30/miniconda3/envs/python3.9/lib/python3.9/site-packages/numpy/core/multiarray.py(736)dot()
    734 
    735 
--> 736 @array_function_from_c_func_and_dispatcher(_multiarray_umath.dot)
    737 def dot(a, b, out=None):
    738     """



ipdb>  s


> /home/jloesch30/miniconda3/envs/python3.9/lib/python3.9/site-packages/numpy/core/multiarray.py(822)dot()
    820 
    821     """
--> 822     return (a, b, out)
    823 
    824 



ipdb>  n


--Return--
(array([51.1 , 25.38, 56.  ]), array([0., 0., 0.]), None)
> /home/jloesch30/miniconda3/envs/python3.9/lib/python3.9/site-packages/numpy/core/multiarray.py(822)dot()
    820 
    821     """
--> 822     return (a, b, out)
    823 
    824 



ipdb>  n


> <__array_function__ internals>(5)dot()



ipdb>  c


> /tmp/ipykernel_51824/1957752173.py(22)fit()
     20             cost = []
     21             for xi, target in zip(X, y):
---> 22                 set_trace()
     23                 cost.append(self._update_weights(xi, target))
     24             avg_cost = sum(cost) / len(y)



ipdb>  X


array([[51.1 , 25.38, 56.  ],
       [57.27, 26.78, 62.  ],
       [49.38, 26.15, 49.  ],
       ...,
       [56.77, 25.22, 49.  ],
       [48.03, 23.11, 32.  ],
       [36.25, 26.95,  8.  ]])


ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(23)fit()
     21             for xi, target in zip(X, y):
     22                 set_trace()
---> 23                 cost.append(self._update_weights(xi, target))
     24             avg_cost = sum(cost) / len(y)
     25             self.cost_.append(avg_cost)



ipdb>  xi


array([57.27, 26.78, 62.  ])


ipdb>  s


--Call--
> /tmp/ipykernel_51824/1957752173.py(53)_update_weights()
     51         self.w_initialized = True
     52 
---> 53     def _update_weights(self, xi, target):
     54         """Apply Adaline learning rule to update the weights"""
     55         set_trace()



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(55)_update_weights()
     53     def _update_weights(self, xi, target):
     54         """Apply Adaline learning rule to update the weights"""
---> 55         set_trace()
     56         output = self.net_input(xi)
     57         error = (target - output)



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(56)_update_weights()
     54         """Apply Adaline learning rule to update the weights"""
     55         set_trace()
---> 56         output = self.net_input(xi)
     57         error = (target - output)
     58         self.w_[1:] += self.eta * xi.dot(error)



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(57)_update_weights()
     55         set_trace()
     56         output = self.net_input(xi)
---> 57         error = (target - output)
     58         self.w_[1:] += self.eta * xi.dot(error)
     59         self.w_[0] += self.eta * error



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(58)_update_weights()
     56         output = self.net_input(xi)
     57         error = (target - output)
---> 58         self.w_[1:] += self.eta * xi.dot(error)
     59         self.w_[0] += self.eta * error
     60         cost = 0.5 * error**2



ipdb>  error


-180688.50678400003


ipdb>  output


182359.50678400003


ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(59)_update_weights()
     57         error = (target - output)
     58         self.w_[1:] += self.eta * xi.dot(error)
---> 59         self.w_[0] += self.eta * error
     60         cost = 0.5 * error**2
     61         return cost



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(60)_update_weights()
     58         self.w_[1:] += self.eta * xi.dot(error)
     59         self.w_[0] += self.eta * error
---> 60         cost = 0.5 * error**2
     61         return cost
     62 



ipdb>  self.w_


array([  -1781.12506784, -102163.9718352 ,  -47734.59331676,
       -110584.31420608])


ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(61)_update_weights()
     59         self.w_[0] += self.eta * error
     60         cost = 0.5 * error**2
---> 61         return cost
     62 
     63     def net_input(self, X):



ipdb>  cost


16324168241.915812


ipdb>  n


--Return--
16324168241.915812
> /tmp/ipykernel_51824/1957752173.py(61)_update_weights()
     59         self.w_[0] += self.eta * error
     60         cost = 0.5 * error**2
---> 61         return cost
     62 
     63     def net_input(self, X):



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(21)fit()
     19                 X, y = self._shuffle(X, y)
     20             cost = []
---> 21             for xi, target in zip(X, y):
     22                 set_trace()
     23                 cost.append(self._update_weights(xi, target))



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(22)fit()
     20             cost = []
     21             for xi, target in zip(X, y):
---> 22                 set_trace()
     23                 cost.append(self._update_weights(xi, target))
     24             avg_cost = sum(cost) / len(y)



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(23)fit()
     21             for xi, target in zip(X, y):
     22                 set_trace()
---> 23                 cost.append(self._update_weights(xi, target))
     24             avg_cost = sum(cost) / len(y)
     25             self.cost_.append(avg_cost)



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(56)_update_weights()
     54         """Apply Adaline learning rule to update the weights"""
     55         set_trace()
---> 56         output = self.net_input(xi)
     57         error = (target - output)
     58         self.w_[1:] += self.eta * xi.dot(error)



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(57)_update_weights()
     55         set_trace()
     56         output = self.net_input(xi)
---> 57         error = (target - output)
     58         self.w_[1:] += self.eta * xi.dot(error)
     59         self.w_[0] += self.eta * error



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(58)_update_weights()
     56         output = self.net_input(xi)
     57         error = (target - output)
---> 58         self.w_[1:] += self.eta * xi.dot(error)
     59         self.w_[0] += self.eta * error
     60         cost = 0.5 * error**2



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(59)_update_weights()
     57         error = (target - output)
     58         self.w_[1:] += self.eta * xi.dot(error)
---> 59         self.w_[0] += self.eta * error
     60         cost = 0.5 * error**2
     61         return cost



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(60)_update_weights()
     58         self.w_[1:] += self.eta * xi.dot(error)
     59         self.w_[0] += self.eta * error
---> 60         cost = 0.5 * error**2
     61         return cost
     62 



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(61)_update_weights()
     59         self.w_[0] += self.eta * error
     60         cost = 0.5 * error**2
---> 61         return cost
     62 
     63     def net_input(self, X):



ipdb>  n


--Return--
68631086878425.83
> /tmp/ipykernel_51824/1957752173.py(61)_update_weights()
     59         self.w_[0] += self.eta * error
     60         cost = 0.5 * error**2
---> 61         return cost
     62 
     63     def net_input(self, X):



ipdb>  n


> /tmp/ipykernel_51824/1957752173.py(21)fit()
     19                 X, y = self._shuffle(X, y)
     20             cost = []
---> 21             for xi, target in zip(X, y):
     22                 set_trace()
     23                 cost.append(self._update_weights(xi, target))



ipdb>  c


> /tmp/ipykernel_51824/1957752173.py(23)fit()
     21             for xi, target in zip(X, y):
     22                 set_trace()
---> 23                 cost.append(self._update_weights(xi, target))
     24             avg_cost = sum(cost) / len(y)
     25             self.cost_.append(avg_cost)



ipdb>  c


> /tmp/ipykernel_51824/1957752173.py(56)_update_weights()
     54         """Apply Adaline learning rule to update the weights"""
     55         set_trace()
---> 56         output = self.net_input(xi)
     57         error = (target - output)
     58         self.w_[1:] += self.eta * xi.dot(error)



ipdb>  c


> /tmp/ipykernel_51824/1957752173.py(22)fit()
     20             cost = []
     21             for xi, target in zip(X, y):
---> 22                 set_trace()
     23                 cost.append(self._update_weights(xi, target))
     24             avg_cost = sum(cost) / len(y)



ipdb>  self.cost


*** AttributeError: 'AdalineSGD' object has no attribute 'cost'


ipdb>  self.cost_


[]


ipdb>  self.cost_


[]


ipdb>  cost


[3317888.0, 16324168241.915812, 68631086878425.83, 1.152554216360185e+17]


In [31]:
new_clf.cost_

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]